### ISSUE TITLE
Default layout for directory

### ISSUE THREAD

**Issue by collimarco** [sitepress/sitepress#41]
Suppose that you have all blog posts inside a `app/content/pages/blog` directory.

If you want to use a "blog" layout, you can set `layout: blog` in the frontmatter of each page.

Is it possible to avoid that duplication and just set the layout once for all the pages inside that directory?

**Comment by collimarco** [comment]
@bradgessler Sorry to bother you directly, but do you have any idea if this can be achieved (set a default layout for a group of pages)?

I have hundreds of files and I would prefer not to add `layout: blog` to each file.

Even if it's not possible, I would love to get a confirmation that is currently not possible.

**Comment by bradgessler** [comment]
I recommend adding `layout: blog` to each page. If its a matter of not wanting to edit those files because you're bringing them over, you could loop through each page on `branch: "version-4"` of the gem, set the layout, and save it like this:

```ruby
Sitepress.configuration.site.root.dig("blog").resources.flatten.select { _1.format == :html }.each { _1.asset.tap { |asset| asset.data["layout"] = "blog" }
.save }
```

Commit all of those files. Then, for any new blog entry, add the `layout: blog` key.

If you really want to do this at runtime then you could manipulate the nodes directly and set the `layout` key to `blog`, but that API is going to change between the current version of Sitepress and the `version-4` branch.

---

Here's the Gemfile that will give you the write API:

```ruby
gem "sitepress", "~> 3.2", github: "sitepress/sitepress", branch: "version-4"
```

**Comment by collimarco** [comment]
Thanks! For now I have added the `layout: blog` to all files.

Maybe it would be nice to be able to configure some default values for the frontmatter for all the files that are in a given directory. What do you think (for the future)?

**Comment by bradgessler** [comment]
Yeah, I think I'd like to have a `.template.html.md` (template dot file) that can be thrown into a directory and new files created there pickup the settings from said file.

For now what I recommend is adding a `./templates` directory to your project and add a task to your `Rakefile` that copies it to where you want it.

**Comment by bradgessler** [comment]
Closing this issue assuming a Rakefile works for templates.

**Comment by collimarco** [comment]
Thanks for the replies. 

My idea was not about the default "generated" files, but more about a config file that contains some default values for the frontmatter and those values are dynamically merged.

For example: add a `default.md` file in a directory with a frontmatter and all the files in that directory get their frontmatter values merged with the default frontmatter (it's like merging two hashes)
