### ISSUE TITLE
categories and tags routes

### ISSUE THREAD

**Issue by adrienpoly** [sitepress/sitepress#55]
I would like to have category and tags to my posts and get dedicated routes

`/posts/categories/rails` would list all articles in the rails category

I don't think there is a builtin way of doing this right now in Sitepress. 

Is the easiest way to build my own custom route and controller for that or is their something in Sitepress I could leverage to achieve that ?

**Comment by bradgessler** [comment]
You have two options:

1. Move Sitepress into Rails and have a Rails controller route to the content.
2. Copy resources via the "Resource Manipulation" API at https://sitepress.cc/basics/traversal

I'm going to close this Issue since it's not a feature request or bug. You can continue in Discussions and link back to this issue for context.
